// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIU_oKHx8-oRFLWlme9zHoc0Clkf96AaI',
    appId: '1:623047614259:ios:6c0a6d75f27516da2ce846',
    messagingSenderId: '623047614259',
    projectId: 'btl-flutter-186ad',
    storageBucket: 'btl-flutter-186ad.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWWmxb1oCzN4G9FdNGTbgawHn78qPfawQ',
    appId: '1:623047614259:web:a831fa1ddaac391e2ce846',
    messagingSenderId: '623047614259',
    projectId: 'btl-flutter-186ad',
    authDomain: 'btl-flutter-186ad.firebaseapp.com',
    storageBucket: 'btl-flutter-186ad.appspot.com',
    measurementId: 'G-WWLFFVKLGZ',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWWmxb1oCzN4G9FdNGTbgawHn78qPfawQ',
    appId: '1:623047614259:web:a831fa1ddaac391e2ce846',
    messagingSenderId: '623047614259',
    projectId: 'btl-flutter-186ad',
    authDomain: 'btl-flutter-186ad.firebaseapp.com',
    storageBucket: 'btl-flutter-186ad.appspot.com',
    measurementId: 'G-WWLFFVKLGZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIU_oKHx8-oRFLWlme9zHoc0Clkf96AaI',
    appId: '1:623047614259:ios:6c0a6d75f27516da2ce846',
    messagingSenderId: '623047614259',
    projectId: 'btl-flutter-186ad',
    storageBucket: 'btl-flutter-186ad.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_GIiMAeuBKJqrA3QUm12kORx09or8qf4',
    appId: '1:623047614259:android:6748db259770699c2ce846',
    messagingSenderId: '623047614259',
    projectId: 'btl-flutter-186ad',
    storageBucket: 'btl-flutter-186ad.appspot.com',
  );

}